F_TARGETS: add automatic mode

diff --git a/ansible_engine b/ansible_engine
--- a/ansible_engine
+++ b/ansible_engine
@@ -422,22 +422,6 @@ F_HOSTFILE(){
 F_TARGETS(){
 	F_LOG "$FUNCNAME" "started with these arguments: $@"
 	
-	# 1. filter out all vars and child sections
-	# 2. get all sections and 1 next line
-	# 3. replace [ with newline
-	# 4. replace ] with comma and empty lines with a /
-	# 5. remove all newlines
-	# 6. replace // with /
-	# 7. replace / with newline
-	# --> steps 4-7 are required to ensure even when 2 sections are written without a space
-	#     between. Example:
-	#	[sec1]
-	#  	[sec2]
-	#  	host
-	#     As we catch always section + 1 next line on step 2 to identify empty sections the above 
-	#     steps ensure we will *NOT* have a result of: "sec1" has host "sec2"
-	# 8. get only these lines containing a comma and something behind (means section has a value)
-	#    this is needed as a section can be empty which shouldnt be shown if!
 	OPTIONS=($(for i in $(egrep -v "(:vars|:children)" "$HOSTFILE" | egrep --group-separator="/" -A1 "^\[.*\]"| tr "[" "\n" |sed -e 's/\]$/,/g;s/^$/\//g'| tr -d "\n" | sed 's#//#/#g' | tr "/" "\n" | egrep ",\w+" | cut -d "," -f1);do echo $i $i off; done))
 	# OPTIONS EXPLANATION ABOVE
 
@@ -446,13 +430,19 @@ F_TARGETS(){
 	else
 		DOPT="$1"
 	fi
-        HOSTSELECTION=$(F_DIALOG --${DOPT} "Please use the space-bar to make your selection:" 30 80 30 "${OPTIONS[@]}" 2>&1 >/dev/tty)
-	HERR=$?
-	F_LOG "$FUNCNAME" "HERR was $HERR"
-	if [ "$HERR" != "0" ];then
-		echo "ABORTED"
+	unset NIGRP
+	NIGRP="$2"
+	if [ -z "$NIGRP" ];then
+	        HOSTSELECTION=$(F_DIALOG --${DOPT} "Please use the space-bar to make your selection:" 30 80 30 "${OPTIONS[@]}" 2>&1 >/dev/tty)
+		HERR=$?
+		F_LOG "$FUNCNAME" "HERR was $HERR"
+		if [ "$HERR" != "0" ];then
+			echo "ABORTED"
+		else
+			echo "$HOSTSELECTION"
+		fi
 	else
-		echo "$HOSTSELECTION"
+		echo "${OPTIONS[@]} | cut -d ' ' -f 1 |grep $NIGRP"
 	fi
 	F_LOG "$FUNCNAME" "finished"
 }
