pors: calculate CIDR/Netmask
Signed-off-by: TF <mail@sedi.one>

diff --git a/pors b/pors
--- a/pors
+++ b/pors
@@ -36,7 +36,7 @@
 ##<br>
 ###############################################################################################################
 VERSIONTYPE=beta
-VERSIONNUM="4.0-22"
+VERSIONNUM="4.0-23"
 VERSION="${VERSIONNUM}-${VERSIONTYPE}"
 ###############################################################################################################
 #
@@ -4413,6 +4413,62 @@ F_DEPLOYVM(){
     F_LOG $FUNCNAME ended
 }
 
+## @fn F_CALCCIDR()
+## @brief Calculates the CIDR of a given netmask
+## @param1 required: the netmask
+F_CALCCIDR(){
+    F_LOG $FUNCNAME "started with $1"
+    unset NETMASK cidr
+
+    NETMASK="$1"
+
+    cidr=0
+    IFS=.
+    for dec in $NETMASK; do
+        case $dec in
+            255) let cidr+=8;;
+            254) let cidr+=7 ; break ;;
+            252) let cidr+=6 ; break ;;
+            248) let cidr+=5 ; break ;;
+            240) let cidr+=4 ; break ;;
+            224) let cidr+=3 ; break ;;
+            192) let cidr+=2 ; break ;;
+            128) let cidr+=1 ; break ;;
+            0) ;;
+            *) echo "Error: $dec is not recognised"; return 3 ;;
+        esac
+    done
+
+    echo "$cidr"
+
+    F_LOG $FUNCNAME "ended with the calculated CIDR: $cidr"
+}
+
+## @fn F_CALCNETMASK()
+## @brief Calculates the NETMASK of a given CIDR
+## @param1 required: the CIDR
+F_CALCNETMASK(){
+    F_LOG $FUNCNAME "started with $1"
+    unset NETMASK CIDR nm
+    CIDR="$1"
+
+    nm=$[2**(32-${CIDR})] # 2^(32-x)
+
+    if ! [ "$[$nm/256**0]" -gt "256" ]; then
+        NETMASK=$(echo "255.255.255.$[256-($nm/256**0)]")
+    elif ! [ "$[$nm/256**1]" -gt "256" ]; then
+        NETMASK=$(echo "255.255.$[256-($nm/256**1)].0")
+    elif ! [ "$[$nm/256**2]" -gt "256" ]; then
+        NETMASK=$(echo "255.$[256-($nm/256**2)].0.0")
+    elif ! [ "$[$nm/256**3]" -gt "256" ]; then
+        NETMASK=$(echo "$[256-($nm/256**3)].0.0.0")
+    fi
+
+    echo "$NETMASK"
+
+    F_LOG $FUNCNAME "ended with the calculated NETMASK: $NETMASK"
+}
+
 ## @fn F_STARTVMDEP()
 ## @brief Deploy a new blank VM based on a template
 ## @exception ..
@@ -4477,16 +4533,16 @@ F_STARTVMDEP(){
 
     while [ $FINISHED -eq 0 ];do
         DIAOUT=$(F_DIALOG --form "\nSetup your new VM - Use arrow keys to switch between\n(no validation so be careful what you type..)" 30 100 20  \
-                "Hostname" 1 1 "$VMHOST" 1 20 70 60  \
-                "Server Domain Name" 2 1 "$VMSDOMAIN" 2 20 70 60 \
-                "CPU count" 3 1 "$VMCPU" 3 20 4 3 \
-                "RAM (GB)" 4 1 "$VMRAM_GB" 4 20 10 10 \
-                "Host IP (or 'dhcp')" 5 1 "$VMIP" 5 20 27 28 \
-                "Netmask (x.x.x.x)" 6 1 "$VMNETMASK" 6 20 27 28 \
-                "Gateway IP" 7 1 "$VMGW" 7 20 27 28 \
-                "DNS #1" 8 1 "$VMDNS1" 8 20 27 28 \
-                "DNS #2" 9 1 "$VMDNS2" 9 20 27 28 \
-                "VM Provider" 10 1 "$VM_PROVIDER" 10 20 70 60  \
+                "Hostname" 1 1 "$VMHOST" 1 25 70 60  \
+                "Server Domain Name" 2 1 "$VMSDOMAIN" 2 25 70 60 \
+                "CPU count" 3 1 "$VMCPU" 3 25 4 3 \
+                "RAM (GB)" 4 1 "$VMRAM_GB" 4 25 10 10 \
+                "Host IP (or 'dhcp')" 5 1 "$VMIP" 5 25 27 28 \
+                "CIDR (0-32) or Netmask" 6 1 "$VMNETMASK" 6 25 27 28 \
+                "Gateway IP" 7 1 "$VMGW" 7 25 27 28 \
+                "DNS #1" 8 1 "$VMDNS1" 8 25 27 28 \
+                "DNS #2" 9 1 "$VMDNS2" 9 25 27 28 \
+                "VM Provider" 10 1 "$VM_PROVIDER" 10 25 70 60  \
                 3>&1 1>&2 2>&3)
         WERR=$?
         [ $WERR -eq 1 ] && F_LOG "$FUNCNAME" "Aborted by user" && ABORTED=1 && FINISHED=1 && return 4
@@ -4507,19 +4563,27 @@ F_STARTVMDEP(){
         VMDNS2=$(echo $NDIAOUT | cut -d "|" -f9 | tr -d " ")
         VM_PROVIDER=$(echo $NDIAOUT | cut -d "|" -f10 | tr -d " ")
 
+        # calculating the CIDR/NETMASK depending on the given value
+        if [ ${#VMNETMASK} -le 2 ]; then
+            VMNETCIDR="$VMNETMASK"
+            VMNETMASK=$(F_CALCNETMASK "$VMNETMASK")
+        else
+            VMNETCIDR=$(F_CALCCIDR "$VMNETMASK")
+        fi
+
         # prepare IaC config
         VMHOSTWDATE="${VMHOST}_$(date +%Y%m%d-%H%M%S)"
         TMPHWPROFILE=$IACDIR/pors_hardware-config_${VMHOSTWDATE}.config
         [ "$HWPROFILE" != "Empty" ] && touch $TMPHWPROFILE
         cp ${HWCONFIG}${HWPROFILE}.config $TMPHWPROFILE
 
-        F_LOG "$FUNCNAME" "VMHOST,VMCPU,VMRAM_GB,,VMRAM_MB,VMIP,VMNETMASK,VMGW,VMDNS1,VMDNS2,VMSDOMAIN,VM_PROVIDER"
-        F_LOG "$FUNCNAME" "$VMHOST,$VMCPU,$VMRAM_GB,$VMRAM_MB,$VMIP,$VMNETMASK,$VMGW,$VMDNS1,$VMDNS2,$VMSDOMAIN,$VM_PROVIDER"
+        F_LOG "$FUNCNAME" "VMHOST,VMCPU,VMRAM_GB,,VMRAM_MB,VMIP,VMNETMASK,VMGW,VMDNS1,VMDNS2,VMSDOMAIN,VM_PROVIDER,VMNETCIDR"
+        F_LOG "$FUNCNAME" "$VMHOST,$VMCPU,$VMRAM_GB,$VMRAM_MB,$VMIP,$VMNETMASK,$VMGW,$VMDNS1,$VMDNS2,$VMSDOMAIN,$VM_PROVIDER,$VMNETCIDR"
 
-        if [ -z "$VMHOST" -o -z "$VMCPU" -o -z "$VMRAM_GB" -o -z "$VMIP" -o -z "$VMNETMASK" -o -z "$VMGW" -o -z "$VMDNS1" -o -z "$VMDNS2" ];then
-            F_DIAERR 9 "A required field is missing.. try again"
+        if [ -z "$VMHOST" -o -z "$VMCPU" -o -z "$VMRAM_GB" -o -z "$VMIP" -o -z "$VMNETMASK" -o -z "$VMGW" -o -z "$VMDNS1" -o -z "$VMDNS2" -o -z "$VMNETCIDR" ];then
+            F_DIAERR 3 "A required field is missing.. try again"
             F_LOG $FUNCNAME "ERROR: A required field is missing!"
-            VMERR=99
+            VMERR=3
         else
             FINISHED=1
             VMERR=0
@@ -4605,6 +4669,7 @@ F_STARTVMDEP(){
             echo "VMRAM_MB=$VMRAM_MB" >> $TMPHWPROFILE
             echo "VMIP=$VMIP" >> $TMPHWPROFILE
             echo "VMNETMASK=$VMNETMASK" >> $TMPHWPROFILE
+            echo "VMNETCIDR=$VMNETCIDR" >> $TMPHWPROFILE
             echo "VMGW=$VMGW" >> $TMPHWPROFILE
             echo "VMDNS1=$VMDNS1" >> $TMPHWPROFILE
             echo "VMDNS2=$VMDNS2" >> $TMPHWPROFILE
@@ -4769,7 +4834,7 @@ F_GOOGLECP_DEPLOY(){
     if [ -z "$VMSDOMAIN" ];then VMHOSTF=$VMHOST; else VMHOSTF="${VMHOST}.${VMSDOMAIN}"; fi
 
     # sum up (makes uses of real tab spaces in dialog):
-    F_DIALOG --no-collapse --colors --yesno "\nPORS is about to provision an instance with the following details:\n\n    GCP Project:"$'\t'"\Zb$VM_GOOGLECP_ID\ZB\n\n    Hostname:"$'\t\t'"${VMHOSTF}\n    CPU:"$'\t\t'"$VMCPU\n    RAM:"$'\t\t'"$VMRAM_GB GB ($VMRAM_MB MB)\n    IP:"$'\t\t'"$VMIP\n    Machine Type:"$'\t'"$VM_GOOGLECP_MTYPE\n    Metadata Role:"$'\t'"$VM_GOOGLECP_MROLE\n    DNS servers:"$'\t'"$VMDNS1, $VMDNS2\n\nDo you want to continue?\n" 30 80
+    F_DIALOG --no-collapse --colors --yesno "\nPORS is about to provision an instance with the following details:\n\n    GCP Project:"$'\t'"\Zb$VM_GOOGLECP_ID\ZB\n\n    Hostname:"$'\t\t'"${VMHOSTF}\n    CPU:"$'\t\t'"$VMCPU\n    RAM:"$'\t\t'"$VMRAM_GB GB ($VMRAM_MB MB)\n    IP:"$'\t\t'"$VMIP/$VMNETCIDR ($VMNETMASK)\n    Machine Type:"$'\t'"$VM_GOOGLECP_MTYPE\n    Metadata Role:"$'\t'"$VM_GOOGLECP_MROLE\n    DNS servers:"$'\t'"$VMDNS1, $VMDNS2\n\nDo you want to continue?\n" 30 80
     DEPLOYIT=$?
 
     [ $DEPLOYIT -ne 0 ] && F_LOG $FUNCNAME "Aborted by user" && $(rm -vf $TMPHWPROFILE >> $LOG 2>&1 &) return 4
@@ -4844,7 +4909,7 @@ F_PROXMOX_DEPLOY(){
     if [ -z "$VMSDOMAIN" ];then VMHOSTF=$VMHOST; else VMHOSTF="${VMHOST}.${VMSDOMAIN}"; fi
 
     # sum up (makes uses of real tab spaces in dialog):
-    F_DIALOG --no-collapse --colors --yesno "\nPORS is about to provision a VM with the following details:\n\n    Proxmox ID:"$'\t'"\Zb$VM_PROXMOX_NODE\ZB\n\n    Hostname:"$'\t\t'"${VMHOSTF}\n    CPU:"$'\t\t'"$VMCPU\n    RAM:"$'\t\t'"$VMRAM_GB GB ($VMRAM_MB MB)\n    IP:"$'\t\t'"$VMIP/$VMNETMASK\n    Gateway:"$'\t\t'"$VMGW\n    DNS servers:"$'\t'"$VMDNS1, $VMDNS2\n    Network:"$'\t\t'"$VCNET\n\nDo you want to continue?\n" 30 80
+    F_DIALOG --no-collapse --colors --yesno "\nPORS is about to provision a VM with the following details:\n\n    Proxmox ID:"$'\t'"\Zb$VM_PROXMOX_NODE\ZB\n\n    Hostname:"$'\t\t'"${VMHOSTF}\n    CPU:"$'\t\t'"$VMCPU\n    RAM:"$'\t\t'"$VMRAM_GB GB ($VMRAM_MB MB)\n    IP:"$'\t\t'"$VMIP/$VMNETCIDR ($VMNETMASK)\n    Gateway:"$'\t\t'"$VMGW\n    DNS servers:"$'\t'"$VMDNS1, $VMDNS2\n    Network:"$'\t\t'"$VCNET\n\nDo you want to continue?\n" 30 80
     DEPLOYIT=$?
 
     [ $DEPLOYIT -ne 0 ] && F_LOG $FUNCNAME "Aborted by user" && return 4
@@ -4884,7 +4949,16 @@ F_PROXMOX_DEPLOY(){
     DISK_LIST_FLAT="${DISK_LIST['all']}"
     F_LOG $FUNCNAME "DISK_LIST:\n${DISK_LIST['all']}"
 
-    F_A2BIN $HOSTFILE $PBPVEDEPLOY "Deploying $VMHOST to $VM_PROVIDER..." "--limit pors_server -e {'px_var':'$VM_PROXMOX_NODE','server_hostname':['${VMHOSTF}'],'server_shortname':'${VMHOST}','server_ram_mb':'$VMRAM_MB','server_cpu_cores_count':'$VMCPU','server_ip':'$VMIP','server_netmask':'$VMNETMASK','server_gateway':'$VMGW','server_dns1':'$VMDNS1','server_dns2':'$VMDNS2','server_domain':'$VMSDOMAIN','server_machine_type':'$VM_GOOGLECP_MTYPE','server_metadata_role':'$VM_GOOGLECP_MROLE','server_disk_type':'${VMDISK1TYPE}','server_disk_num':'$VMDISKCNT','server_disk_sizegb':'${VMDISK1SIZEGB}','server_disk_dev':'${VMDISK1DEV}','server_disk_name':'$VMDISK1NAME','server_disk_gcpdevname':'$VMDISK1EXTRANAME','server_disk_autodel':'$VMDISK1DEVAUTODEL','disks':[${DISK_LIST_FLAT}],'server_disk_bootdev':'${VMDISK1DEVBOOT}'}"
+    # set static ip or dhcp based on the profile
+    if [ "$VMIP" == "dhcp" ];then
+        VMIPCONF="ip=$VMIP"
+    else
+        VMIPCONF="ip=$VMIP/$VMNETMASK,gw=$VMGW"
+    fi
+
+    F_LOG $FUNCNAME "Will use this ip config: $VMIPCONF"
+
+    F_A2BIN $HOSTFILE $PBPVEDEPLOY "Deploying $VMHOST to $VM_PROVIDER..." "--limit pors_server -e {'px_var':'$VM_PROXMOX_NODE','server_hostname':['${VMHOSTF}'],'server_shortname':'${VMHOST}','server_ram_mb':'$VMRAM_MB','server_cpu_cores_count':'$VMCPU','server_ipconfig':'$VMIPCONF','server_dns1':'$VMDNS1','server_dns2':'$VMDNS2','server_domain':'$VMSDOMAIN','server_disk_type':'${VMDISK1TYPE}','server_disk_num':'$VMDISKCNT','server_disk_sizegb':'${VMDISK1SIZEGB}','server_disk_dev':'${VMDISK1DEV}','server_disk_name':'$VMDISK1NAME','server_disk_extraname':'$VMDISK1EXTRANAME','server_disk_autodel':'$VMDISK1DEVAUTODEL','disks':[${DISK_LIST_FLAT}],'server_disk_bootdev':'${VMDISK1DEVBOOT}'}"
     DEPERR=$?
     F_LOG $FUNCNAME "deploying ended with code: $DEPERR"
 
