pors: v4.0-62
- add playbook hook to allow running own pb's during VM deployment
- fix several issues during deployment - especially error handling
- allowing to auto-reboot during VM deployment without bothering the
   user (not selectable - as I do not think that this is needed)
- skip useless unfinished menu when selecting VM-Management
- added a pre-check before starting PORS which ensures ansible.cfg is in place

diff --git a/pors b/pors
--- a/pors
+++ b/pors
@@ -36,7 +36,7 @@
 ##<br>
 ###############################################################################################################
 VERSIONTYPE=RC
-VERSIONNUM="4.0-60"
+VERSIONNUM="4.0-62"
 VERSION="${VERSIONNUM}_${VERSIONTYPE}"
 ###############################################################################################################
 #
@@ -1482,11 +1482,16 @@ F_DIAERR(){
 
 ## @fn F_ERRLOG()
 ## @brief dialog box very similar to F_DIAERR but givin an option to display a given logfile
+## @param1 required: error code number
+## @param2 required: task name / description to show
+## @param3 optional: full path to the log file to show (defaults to $LOG)
 F_ERRLOG(){
         echo "$FUNCNAME started" >> $LOG
         ERRC="$1"
         TASK="$2"
 	DLOG="$3"
+
+        [ -z "$DLOG" ] && DLOG=$LOG
 
         [ -z "$ERRC" ]&&echo ERRORCODE MISSING for $FUNCNAME && F_EXIT
 
@@ -4423,7 +4428,6 @@ F_VSPHERE_DEPLOY(){
 #2>&1 >> $LOG
     DEPERR=$?
     F_LOG $FUNCNAME "deploying ended with code: $DEPERR"
-    #F_DIAERR $DEPERR "Deploying $VMHOST to $VCENTER" 
     [ $DEPERR -ne 0 ] && return 99
 
     if [ $DEPERR -eq 0 ]&&[ "$VMDISK" -ne 0 ];then
@@ -5081,33 +5085,36 @@ F_STARTVMDEP(){
                     ;;
                     *) F_DIAERR 3 "ERROR no valid VM provider selected! Check documentation." && return 3 ;;
             esac
-            F_ERRLOG $VMERR "Deploying $VMHOST" $LOG
-            [ -f "$TMPHWPROFILE" ] && F_DIALOG --yesno "\nDo you want to save the hardware profile for\n\n    $VMHOST\n\nas an IaC (Infrastructure as Code) profile?\n\nWhen you select 'yes' you can re-deploy with the same settings when choosing the 'IaC' folder next time." 16 100
-            if [ $? -eq 1 ];then
-                IACKEEP=0 
-            else
-                IACKEEP=1
-            fi
         else
-            [ $? -eq 1 ] && rm -vf $TMPHWPROFILE >> $LOG 2>&1
+            [ $? -eq 1 ] && IACKEEP=0 
         fi
     done
 
     # install base software not in template, ensure up2date system patches
     if [ $VMERR -eq 0 ];then
         F_BASEINSTALL "${VMHOSTF}" "$TMPHWPROFILE"
-        F_SYSUPGRADE "${VMHOSTF}"
-        F_DIAERR $? "Upgrading System"
+        BERR=$?
+        [ $BERR -ne 0 ] && F_ERRLOG $BERR "Base install" && return $BERR
+        F_SYSUPGRADE "${VMHOSTF}" autoreboot
+        UERR=$?
+        [ $UERR -ne 0 ] && F_ERRLOG $UERR "Upgrading System" && return $UERR
         if [ ! -z "$OS_SERVICE_USER" ];then
             F_ADDSERVICEUSER "${VMHOSTF}"
             F_DIAERR $? "Adding linux service account: $OS_SERVICE_USER"
         fi
         [ $? -eq 0 ] && F_MSG "\n\nCongratulations! Your VM has been successfully deployed and is ready to use now."
+
+        [ -f "$TMPHWPROFILE" ] && F_DIALOG --yesno "\nDo you want to save the hardware profile for\n\n    $VMHOST\n\nas an IaC (Infrastructure as Code) profile?\n\nWhen you select 'yes' you can re-deploy with the same settings when choosing the 'IaC' folder next time." 16 100
+        if [ $? -eq 1 ];then
+            IACKEEP=0 
+        else
+            IACKEEP=1
+        fi
     fi
 
     if [ "$IACKEEP" -ne 1 ];then
         F_LOG $FUNCNAME "deleting IaC file due to a previous error/abort"
-        rm $TMPHWPROFILE
+        rm -vf $TMPHWPROFILE >> $LOG 2>&1
     else
         mv $TMPHWPROFILE $IACDIR/
     fi
@@ -5187,9 +5194,7 @@ F_GOOGLECP_DEPLOY(){
     else
         F_LOG $FUNCNAME "No additional disk config needed"
     fi
-    F_DIAERR $DEPERR "Deploying $VMHOST to $VM_GOOGLECP_ID"
-    [ $DEPERR -ne 0 ] && return 99
-
+    [ $DEPERR -ne 0 ] && F_ERRLOG $DEPERR "Deploying $VMHOST to $VM_GOOGLECP_ID" && return 99
     F_LOG $FUNCNAME ended
 }
 
@@ -5273,9 +5278,7 @@ F_PROXMOX_DEPLOY(){
     else
         F_LOG $FUNCNAME "No additional disk config needed"
     fi
-    F_DIAERR $DEPERR "Deploying $VMHOST to $VM_PROXMOX_NODE"
-    [ $DEPERR -ne 0 ] && return 99
-
+    [ $DEPERR -ne 0 ] && F_ERRLOG $DEPERR "Deploying $VMHOST to $VM_PROXMOX_NODE" && return 99
     F_LOG $FUNCNAME ended
 }
 
@@ -5286,7 +5289,8 @@ F_PROXMOX_DEPLOY(){
 ## @exception Fail: when disk is formatted already
 ## @details Will format all disks specified in the given PORS hardware config
 ## Formatting new disk(s) in an existing system must ensure that param1 is
-## containing just the new disk(s) or that VMDISKFS=skip is set for any existing one
+## containing just the new disk(s) or that VMDISKFS=skip is set for any existing one.
+## WARNING: this will auto-reboot the target system once completed
 F_FORMATDISK(){
     F_LOG $FUNCNAME started
     unset VMDISKCNT
@@ -5344,7 +5348,7 @@ F_FORMATDISK(){
             [ $ERR -ne 0 ] && F_LOG $FUNCNAME "error $ERR occured" && return $ERR
         fi
     done
-    F_SYSREBOOT "$VMHOSTF"
+    F_SYSREBOOT "$VMHOSTF" autoreboot
     F_LOG $FUNCNAME ended
 }
 
@@ -5466,14 +5470,29 @@ F_BASEINSTALL(){
 
     [ -z "$SELHOSTS" ] && F_DIAERR 9 "missing param for $FUNCNAME" && break 99
 
+    unset ABINARGS
+    if [ -f "$TMPHWPROFILE" ];then
+        ABINARGS="-e {'server_hostname':'$VMHOSTF','server_shortname':'$VMHOST','server_dns1':'$VMDNS1','server_dns2':'$VMDNS2','server_domain':'$VMSDOMAIN'}"
+    fi
+
+    # check for playbook hook
+    HOOKYML=$(F_GETANSIBLEVAR hook_system_playbook)
+
+    # install
     for uhost in $(echo "$SELHOSTS" |tr " " "\n" | cut -d ":" -f 1);do
         # check ssh first
         F_CHECKSSH "$uhost"
-        if [ -f "$TMPHWPROFILE" ];then
-            F_ABIN $HOSTFILE $PBBASEINSTALL "Installing base on $uhost ..." "--limit $uhost -e {'server_hostname':'$VMHOSTF','server_shortname':'$VMHOST','server_dns1':'$VMDNS1','server_dns2':'$VMDNS2','server_domain':'$VMSDOMAIN'}"
+        if [ -z "$HOOKYML" ]|| [ "$HOOKYML" == "False" ];then
+            F_LOG $FUNCNAME "No system hook defined"
         else
-            F_ABIN $HOSTFILE $PBBASEINSTALL "Installing base on $uhost ..." "--limit $uhost"
+            F_LOG $FUNCNAME "System hook defined! Will run the following playbook(s): $HOOKYML"
+            for pb in $HOOKYML;do
+                F_ABIN $HOSTFILE $DATADIR/custom/playbooks/$pb "Running SYSTEM PLAYBOOK HOOK ($pb) on $uhost ..." "--limit $uhost $ABINARGS"
+                LERR=$?
+                [ $LERR -ne 0 ] && F_DIAERR $LERR "SYSTEM PLAYBOOK HOOK ($pb) on $uhost\n" && return 3
+            done
         fi
+        F_ABIN $HOSTFILE $PBBASEINSTALL "Installing base on $uhost ..." "--limit $uhost $ABINARGS"
     done
     LERR=$?
     F_DIAERR $LERR "Base install on:\n\n$SELHOSTS\n\n"
@@ -5484,14 +5503,16 @@ F_BASEINSTALL(){
 
 ## @fn F_SYSUPGRADE()
 ## @brief system upgrade tasks
-## @exception ..
-## @details N/A
+## @param1 optional: set the host for the upgrade function
+## @param2 optional: (requires param1!) when set to "autoreboot" it will not ask for reboot after upgrading has finished
+## @details Upgrade a system by the distribution package manager
 F_SYSUPGRADE(){ 
     F_LOG $FUNCNAME started
     GHOST="$1"
     unset AUTOMODE PARENTPID
     export PARENTPID=$BASHPID
     AUTOMODE="$1"
+    AUTOREBOOT=$2
 
     if [ -z "$AUTOMODE" ];then
         SELHOSTS="$(F_SELHOST)"
@@ -5513,8 +5534,8 @@ F_SYSUPGRADE(){
     done
     if [ $FORERR -eq 0 ];then
         if [ $? -eq 0 ];then
-            F_LOG $FUNCNAME "System packages or upgrade(s) have installed for:\n$SELHOSTS\n\nA REBOOT IS REQUIRED!\nReboot handler will be initiated ..."
-            F_SYSREBOOT "$SELHOSTS"
+            F_LOG $FUNCNAME "System packages or upgrade(s) have been installed for:\n$SELHOSTS\n\nA REBOOT IS REQUIRED!\nReboot handler will be initiated ..."
+            F_SYSREBOOT "$SELHOSTS" $AUTOREBOOT
             LASTERR=$?
         else
             F_LOG $FUNCNAME "Rebooting handling skipped by user"
@@ -5529,20 +5550,25 @@ F_SYSUPGRADE(){
 ## @fn F_SYSREBOOT()
 ## @brief reboots a remote system
 ## @param 1 required: the host or a list of hosts (space separated) to be rebooted
+## @param 2 optional: ask for a reboot (empty) or not (when set to: "autoreboot")
 ## @details tbd
 F_SYSREBOOT(){ 
     REBHOSTS="$1"
-    F_LOG $FUNCNAME "started with $REBHOSTS"
+    ASKUSER=$2
+    F_LOG $FUNCNAME "started with $REBHOSTS $ASKUSER"
     [ -z "$REBHOSTS" ] && F_LOG $FUNCNAME "ERROR: no host given" && return 3
-
 
     for host in $REBHOSTS;do
         honly=${host/:*}
-        F_DIALOG --scrollbar --yesno "\n\nThe server\n\n$host\n\nrequires a reboot!\n\nDo you want to initiate a reboot NOW?" 20 50
-        if [ $? -eq 0 ];then
+        if [ $ASKUSER == "autoreboot" ];then
             F_ABIN $HOSTFILE $PBSYSREBOOT "Rebooting $honly ..." "-e {'target':'$honly'}" || break
         else
-            F_LOG "$FUNCNAME" "Skipped rebooting $honly"
+            F_DIALOG --scrollbar --yesno "\n\nThe server\n\n$host\n\nrequires a reboot!\n\nDo you want to initiate a reboot NOW?" 20 50
+            if [ $? -eq 0 ];then
+                F_ABIN $HOSTFILE $PBSYSREBOOT "Rebooting $honly ..." "-e {'target':'$honly'}" || break
+            else
+                F_LOG "$FUNCNAME" "Skipped rebooting $honly"
+            fi
         fi
     done
     FORERR=$?
@@ -5721,7 +5747,7 @@ F_MENUMAIN(){
                         F_LOG $FUNCNAME "F_CONFMENU ended with $?"
                         ;;
                         VM-Management)
-                        F_VMMENU
+                        F_DEPLOYVM
                         F_LOG $FUNCNAME "F_VMMENU ended with $?"
                         ;;
                         "Upgrade System")
@@ -5803,8 +5829,13 @@ fi
 
 echo "starting PORS as user $ME"
 
-# pre-check Ansible reqs
-# check ansible version first
+####  pre-check Ansible reqs
+
+# check ansible variable file existence
+
+[ ! -f $HOME/.ansible.cfg ] && echo -e "\nERROR: missing $HOME/.ansible.cfg. Please ensure you have copied it from EXAMPLES/ansible.cfg\n\ne.g: cp EXAMPLES/ansible.cfg $HOME/.ansible.cfg\n" && exit 4
+
+# check ansible version
 unset AVERSF AVERS A2VERSF A2VERS
 MREQAVERSION=$(echo $REQAVERSION |tr -d ".")
 AVERSF=$($ABIN --version | head -n 1 | egrep -o "[1-9]+\.[0-9]+\.[0-9]+")
